# Generated by Django 2.2.7 on 2019-11-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='name',
            field=models.CharField(blank=True, max_length=25, unique=True),
        ),
    ]
