# Generated by Django 2.2.7 on 2019-11-21 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20191121_0524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='maxAddOns',
        ),
    ]
