# Generated by Django 2.2.7 on 2019-11-21 05:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orderitem_maxaddons'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='maxAddOns',
            field=models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addoncount',
            name='addOnType',
            field=models.ForeignKey(blank=True, default=10, on_delete=django.db.models.deletion.CASCADE, to='orders.AddOnType'),
        ),
    ]
