# Generated by Django 2.2.7 on 2019-11-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_menuitem_maxaddons'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='maxAddOns',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
