# Generated by Django 2.2.7 on 2019-11-13 19:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20191113_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addoncount',
            name='numberOfAddOns',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
