# Generated by Django 2.2.7 on 2019-11-13 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20191113_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='addOnCount',
        ),
        migrations.DeleteModel(
            name='AddOnCount',
        ),
    ]
