# Generated by Django 2.2.7 on 2019-11-20 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_menuitem_maxaddons'),
    ]

    operations = [
        migrations.AddField(
            model_name='addoncount',
            name='addOnType',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='orders.AddOnType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addoncount',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='orders.Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addoncount',
            name='size',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='orders.Size'),
            preserve_default=False,
        ),
    ]
