# Generated by Django 2.2.7 on 2019-12-03 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderItems',
        ),
    ]
